image:
  repository: docker.app.io/obc/profile
  tag: latest
  pullPolicy: Always
  imagePullSecrets: []

service:
  type: ClusterIP

ports:
  - name: http
    targetPort: 5000
    protocol: TCP
    port: 5000
  # - name: admin
  #   targetPort: 3001
  #   protocol: TCP
  #   port: 3001

podAnnotations: {}

autoscaling:
  enabled: false
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

liveness:
  initialDelaySeconds: 120
  periodSeconds: 20
  httpGet:
    path: /healthz
    port: http

readiness:
  initialDelaySeconds: 120
  periodSeconds: 20
  httpGet:
    path: /healthz
    port: http

volumes: {}
  # - name: config
  #   configMap:
  #     name: mongodb-config
  #     items:
  #       - key: mongod.conf
  #         path: mongod.conf

env: 
  - name: NODE_ENV
    value: development
  - name: TZ
    value: Asia/Tehran
  - name: SERVER_PORT
    value: '5000'

envFrom: {}
  # - configMapRef:
  #     name: env-configmap
  # - secretRef:
  #     name: env-secrets

config: 
  enabled: false
  values: {}
    # php.ini: |
    #   global: true
    # hosts: |
    #   127.0.0.1    localhost
    #   32.12.10.32  google.com
    # resolve.cnf: |
    #   nameserver   9.9.9.9

secret:
  enabled: false
  values: {}
    ## echo "salam" | base64
    ## echo "c2FsYW0K" | base64 -d
    # DB_PASSWORD: c2FsYW0K

nodeSelector: {}

tolerations: []

affinity: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  # requests:
  #   memory: "128Mi"
  #   cpu: "250m"
  limits:
    memory: "250Mi"
    cpu: "150m"

command: []
  # - npm
  # - run
  # - start

args: []
  # - --http

ingress:
  enabled: true
  ingressClass: public
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - domain: profile.svc.app.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              # name: DONT NEED => "app.fullname"
              port:
                name: http
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

serviceAccount:
  enabled: false
  name: ""
  create: true
  annotations: {}